// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-videos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_videos_default = defineTool({
  name: "list_videos",
  title: "List videos",
  description: "List videos available in StreamFlex for the signed-in user.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of videos to return."),
    search: z.string().optional().describe("Optional case-insensitive title search.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    let query = supabaseForUser(ctx).from("videos").select("*").order("created_at", { ascending: false }).limit(limit);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { videos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_profile_default = defineTool2({
  name: "get_profile",
  title: "Get my profile",
  description: "Return the signed-in user's StreamFlex profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser2(ctx).from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nrjmxqmshjkthbhlalgc";
var mcp_default = defineMcp({
  name: "streamflex-mcp",
  title: "StreamFlex MCP",
  version: "0.1.0",
  instructions: "Tools for the StreamFlex app. Use `list_videos` to browse the video catalog and `get_profile` to fetch the signed-in user's profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_videos_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
